apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drop-commerce-ingress
  namespace: drop-commerce
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "drop-commerce-ip"
    networking.gke.io/managed-certificates: "drop-commerce-cert"
    networking.gke.io/v1beta1.FrontendConfig: "drop-commerce-frontend-config"
spec:
  rules:
  - host: api.dropcommerce.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
  - host: ws.dropcommerce.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 80

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: drop-commerce-frontend-config
  namespace: drop-commerce
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
